
/*
 * This file is autogenerated by the SqlToCSharp.cs tool. 
 * All modifications will be lost when the tool is ran.
 */ 


using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.IO;
using System.Reflection;

#pragma warning disable 649

namespace MonkeyWrench.DataClasses
{
	public partial class DBLane : DBRecord
	{
		private string _lane;
		private string _source_control;
		private string _repository;
		private string _min_revision;
		private string _max_revision;
		private int? _parent_lane_id;
		private string _commit_filter;
		private bool _traverse_merge;
		private bool _enabled;
		private DateTime? _changed_date;
		private string _additional_roles;
		private int _priority;

		public string @lane { get { return _lane; } set { _lane = value; } }
		public string @source_control { get { return _source_control; } set { _source_control = value; } }
		public string @repository { get { return _repository; } set { _repository = value; } }
		public string @min_revision { get { return _min_revision; } set { _min_revision = value; } }
		public string @max_revision { get { return _max_revision; } set { _max_revision = value; } }
		public int? @parent_lane_id { get { return _parent_lane_id; } set { _parent_lane_id = value; } }
		public string @commit_filter { get { return _commit_filter; } set { _commit_filter = value; } }
		public bool @traverse_merge { get { return _traverse_merge; } set { _traverse_merge = value; } }
		public bool @enabled { get { return _enabled; } set { _enabled = value; } }
		public DateTime? @changed_date { get { return _changed_date; } set { _changed_date = value; } }
		public string @additional_roles { get { return _additional_roles; } set { _additional_roles = value; } }
		public int @priority { get { return _priority; } set { _priority = value; } }


		public override string Table
		{
			get { return "Lane"; }
		}
        

		public override string [] Fields
		{
			get
			{
				return new string [] { "lane", "source_control", "repository", "min_revision", "max_revision", "parent_lane_id", "commit_filter", "traverse_merge", "enabled", "changed_date", "additional_roles", "priority" };
			}
		}
        

	}
}

