
/*
 * This file is autogenerated by the SqlToCSharp.cs tool. 
 * All modifications will be lost when the tool is ran.
 */ 


using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.IO;
using System.Reflection;

#pragma warning disable 649

namespace MonkeyWrench.DataClasses
{
	public partial class DBRevisionWork : DBRecord
	{
		private int _lane_id;
		private int _host_id;
		private int? _workhost_id;
		private int _revision_id;
		private int _state;
		private DateTime _lock_expires;
		private bool _completed;
		private DateTime? _createdtime;
		private DateTime? _assignedtime;
		private DateTime? _startedtime;
		private DateTime? _endtime;
		private int _priority;
		private bool _is_protected;

		public int @lane_id { get { return _lane_id; } set { _lane_id = value; } }
		public int @host_id { get { return _host_id; } set { _host_id = value; } }
		public int? @workhost_id { get { return _workhost_id; } set { _workhost_id = value; } }
		public int @revision_id { get { return _revision_id; } set { _revision_id = value; } }
		public int @state { get { return _state; } set { _state = value; } }
		public DateTime @lock_expires { get { return _lock_expires; } set { _lock_expires = value; } }
		public bool @completed { get { return _completed; } set { _completed = value; } }
		public DateTime? @createdtime { get { return _createdtime; } set { _createdtime = value; } }
		public DateTime? @assignedtime { get { return _assignedtime; } set { _assignedtime = value; } }
		public DateTime? @startedtime { get { return _startedtime; } set { _startedtime = value; } }
		public DateTime? @endtime { get { return _endtime; } set { _endtime = value; } }
		public int @priority { get { return _priority; } set { _priority = value; } }
		public bool @is_protected { get { return _is_protected; } set { _is_protected = value; } }


		public override string Table
		{
			get { return "RevisionWork"; }
		}
        

		public override string [] Fields
		{
			get
			{
				return new string [] { "lane_id", "host_id", "workhost_id", "revision_id", "state", "lock_expires", "completed", "createdtime", "assignedtime", "startedtime", "endtime", "priority", "is_protected" };
			}
		}
        

	}
}

