// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class EditHost {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Table tblData;
	
	protected System.Web.UI.WebControls.TextBox txtID;
	
	protected System.Web.UI.WebControls.TextBox txtHost;
	
	protected System.Web.UI.WebControls.TextBox txtPassword;
	
	protected System.Web.UI.WebControls.DropDownList cmbQueueManagement;
	
	protected System.Web.UI.WebControls.TextBox txtDescription;
	
	protected System.Web.UI.WebControls.TextBox txtArchitecture;
	
	protected System.Web.UI.WebControls.CheckBox chkEnabled;
	
	protected System.Web.UI.WebControls.Button cmdSave;
	
	protected System.Web.UI.WebControls.Button cmdDeleteAllWork;
	
	protected System.Web.UI.WebControls.Button cmdClearAllWork;
	
	protected System.Web.UI.WebControls.Label lblPasswordWarning;
	
	protected System.Web.UI.WebControls.Label lblMessage;
	
	protected System.Web.UI.WebControls.Table tblLanes;
	
	protected System.Web.UI.WebControls.Table tblMasters;
	
	protected System.Web.UI.WebControls.DropDownList cmbMasterHosts;
	
	protected System.Web.UI.WebControls.LinkButton cmdAddMasterHost;
	
	protected System.Web.UI.WebControls.Table tblSlaves;
	
	protected MonkeyWrench.Web.UI.EnvironmentVariablesEditor editorVariables;
	
	protected System.Web.UI.HtmlControls.HtmlGenericControl lblConfiguration;
}
