// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class EditLaneFile {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.TextBox txtEditor;
	
	protected System.Web.UI.WebControls.Button cmdSave;
	
	protected System.Web.UI.WebControls.Button cmdCancel;
	
	protected System.Web.UI.WebControls.TextBox txtRoles;
	
	protected System.Web.UI.WebControls.ListBox lstLanes;
}
