// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class EditLane {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Label lblH2;
	
	protected System.Web.UI.WebControls.TextBox txtID;
	
	protected System.Web.UI.WebControls.TextBox txtLane;
	
	protected System.Web.UI.WebControls.DropDownList cmbSourceControl;
	
	protected System.Web.UI.WebControls.TextBox txtRepository;
	
	protected System.Web.UI.WebControls.TextBox txtCommitFilter;
	
	protected System.Web.UI.WebControls.TextBox txtMinRevision;
	
	protected System.Web.UI.WebControls.TextBox txtMaxRevision;
	
	protected System.Web.UI.WebControls.TextBox txtTags;
	
	protected System.Web.UI.WebControls.DropDownList lstParentLane;
	
	protected System.Web.UI.WebControls.Label lblChildLanes;
	
	protected System.Web.UI.WebControls.CheckBox chkTraverseMerges;
	
	protected System.Web.UI.WebControls.CheckBox chkEnabled;
	
	protected System.Web.UI.WebControls.Button cmdSave;
	
	protected System.Web.UI.WebControls.Button cmdDeleteAllWork;
	
	protected System.Web.UI.WebControls.Button cmdClearAllWork;
	
	protected System.Web.UI.WebControls.Button cmdDeleteAllRevisions;
	
	protected System.Web.UI.WebControls.Button cmdDontDoWork;
	
	protected System.Web.UI.WebControls.Table tblDependencies;
	
	protected System.Web.UI.WebControls.Table tblCommands;
	
	protected System.Web.UI.WebControls.Table tblFiles;
	
	protected System.Web.UI.WebControls.Table tblHosts;
	
	protected MonkeyWrench.Web.UI.EnvironmentVariablesEditor editorVariables;
	
	protected System.Web.UI.WebControls.Table tblNotifications;
	
	protected System.Web.UI.WebControls.DropDownList cmbNotifications;
	
	protected System.Web.UI.WebControls.LinkButton lnkAddNotification;
	
	protected System.Web.UI.WebControls.Label lblMessage;
}
