// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonkeyWrench.Web.UI {
	
	
	public partial class ErrorPage {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Label errorHeader;
		
		protected System.Web.UI.WebControls.Label errorDescription;
	}
}
