// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Identities {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Table tblIrcIdentities;
	
	protected System.Web.UI.WebControls.TextBox txtIrcName;
	
	protected System.Web.UI.WebControls.TextBox txtIrcServers;
	
	protected System.Web.UI.WebControls.TextBox txtPassword;
	
	protected System.Web.UI.WebControls.CheckBox chkUseSsl;
	
	protected System.Web.UI.WebControls.TextBox txtIrcChannels;
	
	protected System.Web.UI.WebControls.CheckBox chkJoinChannels;
	
	protected System.Web.UI.WebControls.TextBox txtIrcNicks;
	
	protected System.Web.UI.WebControls.LinkButton lnkIrcAdd;
	
	protected System.Web.UI.WebControls.Table tblEmailIdentities;
	
	protected System.Web.UI.WebControls.TextBox txtEmailName;
	
	protected System.Web.UI.WebControls.TextBox txtEmailEmail;
	
	protected System.Web.UI.WebControls.TextBox txtEmailPassword;
	
	protected System.Web.UI.WebControls.LinkButton lnkEmailAdd;
	
	protected System.Web.UI.WebControls.Label lblMessage;
}
