// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Master {
	
	protected System.Web.UI.HtmlControls.HtmlLink cssSkin;
	
	protected System.Web.UI.HtmlControls.HtmlLink idFavicon;
	
	protected System.Web.UI.HtmlControls.HtmlImage imgLogo;
	
	protected System.Web.UI.WebControls.Literal cellLogin;
	
	protected System.Web.UI.WebControls.Literal cellUploadStatus;
	
	protected System.Web.UI.HtmlControls.HtmlGenericControl adminmenu;
	
	protected System.Web.UI.WebControls.Literal cellLogout;
	
	protected System.Web.UI.WebControls.Table tableMainTree;
	
	protected System.Web.UI.WebControls.Table tableHostStatus;
	
	protected System.Web.UI.HtmlControls.HtmlForm form1;
	
	protected System.Web.UI.WebControls.ContentPlaceHolder content;
}
