// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Notifications {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Repeater notificationsRepeater;
	
	protected System.Web.UI.WebControls.LinkButton notificationRemove;
	
	protected System.Web.UI.WebControls.TextBox txtName;
	
	protected System.Web.UI.WebControls.DropDownList cmbIdentity;
	
	protected System.Web.UI.WebControls.DropDownList cmbMode;
	
	protected System.Web.UI.WebControls.DropDownList cmbNotificationType;
	
	protected System.Web.UI.WebControls.LinkButton lnkAdd;
	
	protected System.Web.UI.WebControls.Label lblMessage;
}
