// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class User {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Table tblUser;
	
	protected System.Web.UI.WebControls.TextBox txtUserName;
	
	protected System.Web.UI.WebControls.TextBox txtFullName;
	
	protected System.Web.UI.WebControls.TextBox txtPassword;
	
	protected System.Web.UI.WebControls.TextBox txtRoles;
	
	protected System.Web.UI.WebControls.TextBox txtIRCNicks;
	
	protected System.Web.UI.WebControls.Button cmdSave;
	
	protected System.Web.UI.WebControls.Label lblMessage;
}
